datasets/ONS-UK-trade-in-goods-by-industry-country-and-commodity/exports.py
datasets/ONS-UK-trade-in-goods-by-industry-country-and-commodity/imports.py
datasets/ONS-UK-trade-in-goods-by-industry-country-and-commodity/main.py

Name of the ticket : ONS-UK-trade-in-goods-by-industry-country-and-commodity.
The ticket has three python files.
1.main.py
2.exports.py
3.imports.py
The exports.py deals with exports dataset.
The import.py deals with imports dataset.
main.py concatenates both exports.py and imports.py
Cubes class is added to main.py

Pmd3 pmd4 trade data

---

datasets/ONS-International-Trade-in-Services/main.py
datasets/ONS_ABS/main.py

1.Added family attribute to dataset object.
2.Added Cubes Class.
3.Removed CSVW code snippet.

Ticket Name:ONS_ABS(Annual Business Survey Exporters and Importers)

---

datasets/ONS_BoP/main.py
datasets/ONS_BoP/old_main.py
datasets/ONS_BoP_individual_countries/main.py

Transform done on all sheets instead of one
Cube class added

ONS_BoP: Rework done on script

---

datasets/ONS-UK-trade-in-services/main.py

1.Rewritten the pipeline using databaker
2.Added cubes class
3.Added tracer

ONS-UK-Trade-in-Services

---

datasets/ONS-Trade-in-goods/exports.py
datasets/ONS-Trade-in-goods/imports.py
datasets/ONS-Trade-in-goods/main.py

Rework done on scripts
exports.py and imports.py called up on main.py
Cube class added

ONS-Trade-in-goods

---

datasets/ONS-REUK-Service/main.py

Rework done on script
Cube class added
Trace annotation added

ONS-REUK-Service

---

datasets/ONS-International-Trade-in-Services/main.py

1.Added cubes class
2.Removed warnings

ONS-International-trade-in-Services

---

datasets/HMRC_Trade/main.py

1.Rewritten pipeline using Databaker
2.Added cubes class
3.Added tracer

HMRC-Trade

---

datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/B1.py
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/B2_B2A_B3_B3A.py
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/B4_B4A_B4B.py
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/B5_B5A.py
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/B6B_B6B2_B6B3_B6C_B6C2_B6C3.py
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/B6_B6A.py
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/B7_B7A.py
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/main.py

Rework done on codes
Cubes class added

 ONS-UK-Economic-Accounts-balance-of-payments-current-account

---

datasets/ONS_CPA/.gitignore
datasets/ONS_CPA/main.py

Fixes #18
Lots of motion has been chucked from this, including most of the validation. This moves Issue 18 onto codelist work and the data manager. The CDID provide the lookup for the additional attributes which are present in trade alpha.
Instead of interpreting the colon separated values to provide data which isn't even in the end result I've just removed the field(s).

ONS_CPA: PMD3 to PMD4 Migration

---

datasets/HMRC-alcohol-bulletin/main.py

example of looping with a condition with databaker.

refactor with loop

---

datasets/ONS-Quarterly-country-and-regional-GDP/info.json
datasets/ONS-Quarterly-country-and-regional-GDP/spec.md
reference/measures.csv

https://github.com/GSS-Cogs/family-trade/issues/85

Setting measures and codelists on Issue #85

---

datasets/ONS_MRETS/main.py

Added cube class, did not add tracer due to complexity of code; minimal validation of code lists.

ONS_MRETS (Minimal refactoring)

---

datasets/ONS-UK-Trade-in-goods-CPA-08/main.py

Re: https://github.com/GSS-Cogs/family-trade/pull/140
Transform re-written to meet the requirements on the spec provided for Stage 2 - transform.
If the records wherein the CDID is empty are not required, line 79 of main.py can be uncommented.
https://github.com/GSS-Cogs/family-trade/issues/15

ONS-UK-Trade-in-goods-CPA-08

---

datasets/HMRC-regional-trade-statistics/Jenkinsfile
datasets/HMRC-regional-trade-statistics/info.json
datasets/HMRC-regional-trade-statistics/main.py

* New dataset-specific Jenkinsfile
* accretive upload set to true
* formatting
* added graph name coining

HMRC-regional-trade-statistics

---

datasets/ONS_ABS/main.py

1. Tabs are transformed according to its patterns
2. Few changes to codes
#246

ONS_ABS #246

---

datasets/HMRC-alcohol-bulletin/info.json
datasets/HMRC-alcohol-bulletin/main.py

1. Measure production is replaced by tax
2. Measure type hectolitres is replaced by hectolitres of alcohol
3. Made changes to replace URI's with appropriate values
4. Made changes to suppressed and other values related to marker column
5. Separated beer and cider in Alcohol Type
6. Observation value is rounded to two decimal places
#260

HMRC-alcohol-bulletin

---

datasets/ONS-UK-SA-Trade-in-goods/info.json
datasets/ONS-UK-SA-Trade-in-goods/main.py

1. CSVCubed uplift .
2. Added unit and Measure values in transformation in line with info.json
3. Made code changes in transformation and post processing
#298

ONS-UK-SA-Trade-in-goods

---

datasets/ONS-International-trade-in-services-by-subnational-areas-of-the-UK/info.json
datasets/ONS-International-trade-in-services-by-subnational-areas-of-the-UK/main.py

1. Made code changes.
2. Made changes to info.json
3. uplifted to use CSVCubed
4. Removed unwanted for and if loops
#248

ONS-International-trade-in-services-by-subnational-areas-of-the-UK

---

datasets/ONS-pink-book-trade-in-services/info.json
datasets/ONS-pink-book-trade-in-services/main.py

1. CSVCube uplift
2. Made changes to codelists mapping
3. Made code changes in transformation
4. Removed unwanted codes
#289
#280

ONS-pink-book-trade-in-services

---

datasets/ONS-GDP-at-current-prices-real-time-database-YBHA/info.json
datasets/ONS-GDP-at-current-prices-real-time-database-YBHA/main.py

1. Pipeline rewritten
2. CSVCube uplift
3. Changes to post processing
4. Checked duplicate key errors
#287 
#276

ONS-GDP-at-current-prices-real-time-database-YBHA failed

---

datasets/ONS-Quarterly-country-and-regional-GDP/info.json
datasets/ONS-Quarterly-country-and-regional-GDP/main.py

1. Rewrote the pipeline
2. Made changes to codelists mapping
3. Checked and dropped duplicate values
4. CSVCube uplift
5. Post processing done
#269
#233

ONS-Quarterly-country-and-regional-GDP

---

datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/capital_account-info.json
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/info.json
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/main.py
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/primary_income-info.json
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/quarterly_summary_of_balance_of_payments-info.json
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/secondary_income-info.json
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/trade_in_goods_and_services-info.json
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/transactions_with_eu_and_emu-info.json
datasets/ONS-UK-Economic-Accounts-balance-of-payments-current-account/transactions_with_non_eu-info.json

1. CSV Cube uplift completed
2. Multiple cubes -  transformation code changes
3. Scripted multiple new info.json related to respective cubes
#359 
#356

ONS-UK-Economic-Accounts-balance-of-payments-current-account
